### ISSUE TITLE
Issue still persists. no results are returned.

### ISSUE THREAD

**Issue by Inside4ndroid** [cool-dev-guy/vidsrc-api#10]
Please re-open this issue if the problem still exist.

_Originally posted by @cool-dev-guy in https://github.com/cool-dev-guy/vidsrc-api/issues/8#issuecomment-2028540899_
            
i have re-deployed to vercel and run locally but still no results are returned i have tried several different tmdb id's to be sure too.

![Screenshot 2024-03-31 093251](https://github.com/cool-dev-guy/vidsrc-api/assets/65467186/6167b0e6-6ad0-40d2-b90a-24b894d463e5)

**Comment by cool-dev-guy** [comment]
@Inside4ndroid try now.

**Comment by Inside4ndroid** [comment]
awsome all working now thanks..
