### ISSUE TITLE
Usage of the tool

### ISSUE THREAD

**Issue by francqz31** [cool-dev-guy/vidsrc-api#11]
Hey amazing repo , and really useful. I was wondering how can I use this to scrape movies out of https://fmoviesz.to/home since this website uses vidsrc as a primary provider for almost everything it has.

**Comment by Inside4ndroid** [comment]
> Hey amazing repo , and really useful. I was wondering how can I use this to scrape movies out of https://fmoviesz.to/home since this website uses vidsrc as a primary provider for almost everything it has.

the api works based on tmdbid so you would have to find a way to get the id for the movie on fmovies and then pass the id of the movie to this api

**Comment by francqz31** [comment]
well yeah that's the tricky part

**Comment by cool-dev-guy** [comment]
> well yeah that's the tricky part

yea but its easy than you think,you can just scrape their website and get the imdb id of the item and pass it to this api.
