### ISSUE TITLE
Non Python Dev

### ISSUE THREAD

**Issue by DevJedis** [cool-dev-guy/vidsrc-api#12]
Hello, great work. I don't work with Python nor Node nor Vercel and I've had a hard time tryin to make this even work on Vercel as I've just created an account. Could someone list the detailed steps to make this work in Vercel as this is the lovely message I keep getting:
```
WARN! Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
Error: Unable to find any supported Python versions.
Learn More: http://vercel.link/python-version
```

I don't even know where you people are getting the Node version settings from because I don't see anything in Vercel of the sort. I'd appreciate help on a detailed step for this. Thank you

**Comment by cool-dev-guy** [comment]
> Hello, great work. I don't work with Python nor Node nor Vercel and I've had a hard time tryin to make this even work on Vercel as I've just created an account. Could someone list the detailed steps to make this work in Vercel as this is the lovely message I keep getting:
> 
> ```
> WARN! Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
> Error: Unable to find any supported Python versions.
> Learn More: http://vercel.link/python-version
> ```
> 
> I don't even know where you people are getting the Node version settings from because I don't see anything in Vercel of the sort. I'd appreciate help on a detailed step for this. Thank you

You can:
1. go to your deployment `settings`.
2. There sill be an option like `node` version,which will be `20.x` by default,change it to `18.x`.
3. Then redeploy your deployment to see the results.

Or:
The best way is to google "How to change the node version in vercel."
