### ISSUE TITLE
Sorry, you have been blocked?

### ISSUE THREAD

**Issue by Inside4ndroid** [cool-dev-guy/vidsrc-api#15]
hi how would i get around this ? i have tried a vpn and proxies etc but it still says this from cloudflare?

an y help or ideas would be great :)

![Screenshot 2024-04-04 125912](https://github.com/cool-dev-guy/vidsrc-api/assets/65467186/e0c19750-4d44-447f-b5d5-ca9d5faf0861)

**Comment by rahuloberai** [comment]
> hi how would i get around this ? i have tried a vpn and proxies etc but it still says this from cloudflare?
> 
> 
> 
> an y help or ideas would be great :)
> 
> 
> 
> ![Screenshot 2024-04-04 125912](https://github.com/cool-dev-guy/vidsrc-api/assets/65467186/e0c19750-4d44-447f-b5d5-ca9d5faf0861)
> 
> 
You need to pass origin in headers. 

For example Please have a look

https://hello-world-lively-sun-b454.justchill.workers.dev/?url=https://gamn.vid109d224.site/_v2-remg/12a3c523f8105800ed8c394685aeeb0bc72eae5c58e4fce848437baea93ece832257df1a4b6125fcfa38c35da05dee86aad28d46d73fc4e9d4e5a13f5277f1d5749544f85d4faf5a449df3ec38163946353dc5774c562cd196cfbc0bc9a07ecd2c0fe4101660/h/afddca4/aabe;15a38634f803584ba8926411d7bee906856cab0654b5b8.m3u8&referer=https%3A%2F%2Fe69975b881.nl

Add referer in query string.

**Comment by dallasrol** [comment]
> You need to pass origin in headers.
> 
> For example Please have a look
> 
> https://hello-world-lively-sun-b454.justchill.workers.dev/?url=https://gamn.vid109d224.site/_v2-remg/12a3c523f8105800ed8c394685aeeb0bc72eae5c58e4fce848437baea93ece832257df1a4b6125fcfa38c35da05dee86aad28d46d73fc4e9d4e5a13f5277f1d5749544f85d4faf5a449df3ec38163946353dc5774c562cd196cfbc0bc9a07ecd2c0fe4101660/h/afddca4/aabe;15a38634f803584ba8926411d7bee906856cab0654b5b8.m3u8&referer=https%3A%2F%2Fe69975b881.nl
> 
> Add referer in query string.

Hello can share how to pass origin in headers ??
how about this
`<?php
// Set the appropriate headers for CORS
header("Access-Control-Allow-Origin: http://example.com"); // Change this to your allowed origin
header("Access-Control-Allow-Methods: GET, POST, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type");
?>`

**Comment by cool-dev-guy** [comment]
probably a proxy issue,please reopen the issue if you have any doubts.

**Comment by dallasrol** [comment]
> > hi how would i get around this ? i have tried a vpn and proxies etc but it still says this from cloudflare?
> > an y help or ideas would be great :)
> > ![Screenshot 2024-04-04 125912](https://private-user-images.githubusercontent.com/65467186/319573899-e0c19750-4d44-447f-b5d5-ca9d5faf0861.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NzQ5NjMsIm5iZiI6MTcxMjk3NDY2MywicGF0aCI6Ii82NTQ2NzE4Ni8zMTk1NzM4OTktZTBjMTk3NTAtNGQ0NC00NDdmLWI1ZDUtY2E5ZDVmYWYwODYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDAyMTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzYzQwZTMyYzNhMGJmMzkyMTdkNDk5NjZiZDQ1NzcxNjYyNGM4MWY2NDc2Zjg0YjU4NGM2NGY1MWU3N2EyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bFCLrerNndqCxfaxJCAYCRDnMm7zjQoxqdHDo6pXQZI)
> 
> You need to pass origin in headers.
> 
> For example Please have a look
> 
> https://hello-world-lively-sun-b454.justchill.workers.dev/?url=https://gamn.vid109d224.site/_v2-remg/12a3c523f8105800ed8c394685aeeb0bc72eae5c58e4fce848437baea93ece832257df1a4b6125fcfa38c35da05dee86aad28d46d73fc4e9d4e5a13f5277f1d5749544f85d4faf5a449df3ec38163946353dc5774c562cd196cfbc0bc9a07ecd2c0fe4101660/h/afddca4/aabe;15a38634f803584ba8926411d7bee906856cab0654b5b8.m3u8&referer=https%3A%2F%2Fe69975b881.nl
> 
> Add referer in query string.

your link not working please check !!

![image](https://github.com/cool-dev-guy/vidsrc-api/assets/163819040/9c5cc8c7-eef9-4720-a7cc-a55cb6012bc4)

can you tell me how to deploy [m3u8CloudflareWorkerProxy]
