### ISSUE TITLE
Getting 'This Serverless Function has crashed' in Vercel

### ISSUE THREAD

**Issue by RageshAntony** [cool-dev-guy/vidsrc-api#19]
I deployed my forked repo in Vercel but I got this error

<img width="518" alt="image" src="https://github.com/cool-dev-guy/vidsrc-api/assets/36100215/55c8c18c-58d9-4c6e-9e61-afb1f18e204d">

Logs:

<img width="1418" alt="image" src="https://github.com/cool-dev-guy/vidsrc-api/assets/36100215/c8b9dd5c-7fbb-406a-ab4f-3cf2f27221da">

Why? I followed your steps. (I didn't get any build error)

This is my repo:
https://github.com/RageshAntony/vidsrc-api-stermio.git

I am using Redis to store URLs until it expires. (check for expiry and get new if expired )

please help me

**Comment by RageshAntony** [comment]
I fixed the issue. It's Redis connection issue.

**Comment by RageshAntony** [comment]
@cool-dev-guy 

The code not working suddenly 

the retrieved URLs not suddenly working

https://ewal.v44381c4b81.site/_v2-wwdo/12a3c523fe105800ed8c394685aeeb0b902ea15c58e4bfed0b197baea93ece832257df1a4b6125fcfa38c35da05dee86aad28d46d73fc4e9d4e5a53b5277f1d634c711e30918b40a13c1b4bc6e4e7d11662686271c4675c39085fb09cea322992b15f541532ba10eabbb/h/list;15a38634f803584ba8926411d7bee906856cab0654b5bfb3.m3u8

retrived URLs now not working

**Comment by 2004durgesh** [comment]
> @cool-dev-guy
> 
> The code not working suddenly
> 
> the retrieved URLs not suddenly working
> 
> https://ewal.v44381c4b81.site/_v2-wwdo/12a3c523fe105800ed8c394685aeeb0b902ea15c58e4bfed0b197baea93ece832257df1a4b6125fcfa38c35da05dee86aad28d46d73fc4e9d4e5a53b5277f1d634c711e30918b40a13c1b4bc6e4e7d11662686271c4675c39085fb09cea322992b15f541532ba10eabbb/h/list;15a38634f803584ba8926411d7bee906856cab0654b5bfb3.m3u8
> 
> retrived URLs now not working

did u found any way to work this around since i'm also getting same issue

**Comment by cool-dev-guy** [comment]
New repo : https://github.com/cool-dev-guy/vidsrc.ts
