### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by gabinfinity** [cool-dev-guy/vidsrc-api#2]
Hello everything is fine? Congratulations on the API, I really liked it. Would you like to request some features?

The first would be to change the key extractor to this

https://raw.githubusercontent.com/Ciarands/worstsource-keys/keys/keys.json

Claudemiro's isn't working very well.

And I would like to know if it is possible to return the subtitles in .srt format, that way I can integrate them into my website.

Thank you

**Comment by gabinfinity** [comment]
By the way, I'm not able to run the API on my VPS. Can you help me? I run python main.py but nothing happens

![image](https://github.com/cool-dev-guy/vidsrc-api/assets/59806981/afebe127-bf8f-402b-9f19-2226d3429274)

**Comment by gabinfinity** [comment]
Just a bug report: Sometimes the vidsrc.me url is not decrypting correctly
![image](https://github.com/cool-dev-guy/vidsrc-api/assets/59806981/54ee11b9-5baa-4f07-9e0f-fe412a5f188a)

**Comment by cool-dev-guy** [comment]
Yea i will change the keys in github(the api has already been changed,so its working),to host it on vps you need to use uvicorn(search for deploying fastapi),it works on vercel because its serverless function.

**Comment by gabinfinity** [comment]
Oh okay, im hosting it on vercel by now :D

**Comment by cool-dev-guy** [comment]
> Just a bug report: Sometimes the vidsrc.me url is not decrypting correctly ![image](https://private-user-images.githubusercontent.com/59806981/298151148-54ee11b9-5baa-4f07-9e0f-fe412a5f188a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2ODYxODgsIm5iZiI6MTcwNTY4NTg4OCwicGF0aCI6Ii81OTgwNjk4MS8yOTgxNTExNDgtNTRlZTExYjktNWJhYS00ZjA3LTllMGYtZmU0MTJhNWYxODhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE3MzgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmODM0ZWU2NTYyNjVjNTcwM2ZiZDBjZjQ4YmUyODM3YTgwOWQwMGJmZGQ3ZTg5MDRhMDdmNmQzYzkxY2Y3YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bxH2CqupPvZH_jjjwcUHpuZHXJqe9vmMaVIhjD5zKrQ)

Yea its actually a decode error,there's nothing that can be done actually to get the correct stream url,the code before didnt even worked as better as this version,the only way to get the correct url is reloading,i have commented out a line in the code which will show an error code if the url is broken as above.

**Comment by cool-dev-guy** [comment]
> > Just a bug report: Sometimes the vidsrc.me url is not decrypting correctly ![image](https://private-user-images.githubusercontent.com/59806981/298151148-54ee11b9-5baa-4f07-9e0f-fe412a5f188a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2ODYzMDEsIm5iZiI6MTcwNTY4NjAwMSwicGF0aCI6Ii81OTgwNjk4MS8yOTgxNTExNDgtNTRlZTExYjktNWJhYS00ZjA3LTllMGYtZmU0MTJhNWYxODhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE3NDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlOWNiZGE3ZTA1OWM5N2QzZjE4ODAyOGM2NzA3NDc3N2Y3MzAzNmYxYTg1NDY4Y2IwMjQyZjMzMTNlMzk5MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gJjMi13I_zyJXELC8BsZFpO6FTY4MkXm9oFOMAP0TcI)
> 
> About this problem, this is happening a lot with me, i dont know why, but after some refresh it back to normal, but can happen again with another movie/tv show

its actually due to wrong padding and mistakes in the b64 encoded data,and the algorithm that i use(from Ciarands) has the same error,so i added an online tool to decode it,so it will somehow work more efficiently than the stdlib(base64).

**Comment by cool-dev-guy** [comment]
I think will add more sources so it wouldnt be an issue :)

**Comment by gabinfinity** [comment]
> I think will add more sources so it wouldnt be an issue :)

i saw something about vidsrc.to, is it working? I think vidsrc.me have more content than vidsrc.to, and vidsrc.to needs cors proxy to work. Hope we can find a solution for b64 problem

**Comment by gabinfinity** [comment]
> > Just a bug report: Sometimes the vidsrc.me url is not decrypting correctly ![image](https://private-user-images.githubusercontent.com/59806981/298151148-54ee11b9-5baa-4f07-9e0f-fe412a5f188a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2ODYxODgsIm5iZiI6MTcwNTY4NTg4OCwicGF0aCI6Ii81OTgwNjk4MS8yOTgxNTExNDgtNTRlZTExYjktNWJhYS00ZjA3LTllMGYtZmU0MTJhNWYxODhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE3MzgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmODM0ZWU2NTYyNjVjNTcwM2ZiZDBjZjQ4YmUyODM3YTgwOWQwMGJmZGQ3ZTg5MDRhMDdmNmQzYzkxY2Y3YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bxH2CqupPvZH_jjjwcUHpuZHXJqe9vmMaVIhjD5zKrQ)
> 
> Yea its actually a decode error,there's nothing that can be done actually to get the correct stream url,the code before didnt even worked as better as this version,the only way to get the correct url is reloading,i have commented out a line in the code which will show an error code if the url is broken as above.

where is the line? i would like to add a error code for my site try again to scrap when it return error

**Comment by gabinfinity** [comment]
well vidsrc.me just added CORS for urls, rip

**Comment by cool-dev-guy** [comment]
> > > Just a bug report: Sometimes the vidsrc.me url is not decrypting correctly ![image](https://private-user-images.githubusercontent.com/59806981/298151148-54ee11b9-5baa-4f07-9e0f-fe412a5f188a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2ODYxODgsIm5iZiI6MTcwNTY4NTg4OCwicGF0aCI6Ii81OTgwNjk4MS8yOTgxNTExNDgtNTRlZTExYjktNWJhYS00ZjA3LTllMGYtZmU0MTJhNWYxODhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE3MzgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmODM0ZWU2NTYyNjVjNTcwM2ZiZDBjZjQ4YmUyODM3YTgwOWQwMGJmZGQ3ZTg5MDRhMDdmNmQzYzkxY2Y3YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bxH2CqupPvZH_jjjwcUHpuZHXJqe9vmMaVIhjD5zKrQ)
> > 
> > 
> > Yea its actually a decode error,there's nothing that can be done actually to get the correct stream url,the code before didnt even worked as better as this version,the only way to get the correct url is reloading,i have commented out a line in the code which will show an error code if the url is broken as above.
> 
> where is the line? i would like to add a error code for my site try again to scrap when it return error

Uncomment this line and pass an error code ,so that you can request again.If the url is truncated then the `.m3u8` will not be there so you can do this troubleshooting method.
```python
# hls_url = "TRUNCATED, REQUEST AGAIN" if 'm3u8' not in hls_url else hls_url
```

**Comment by gabinfinity** [comment]
Okay. My API is returning sometimes error 500, do you know what is happening?

![image](https://github.com/cool-dev-guy/vidsrc-api/assets/59806981/708911a9-bf8a-4ef6-8653-48d598891434)

`[ERROR] AttributeError: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/var/task/vc__handler__python.py", line 305, in vc_handler
    response = asgi_cycle(__vc_module.app, body)
  File "/var/task/vc__handler__python.py", line 208, in __call__
    loop.run_until_complete(asgi_task)
  File "/var/lang/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/var/task/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/var/task/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/var/task/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/var/task/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/var/task/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/var/task/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/var/task/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/var/task/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/var/task/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/var/task/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/var/task/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/var/task/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/var/task/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "./main.py", line 76, in source
    results = await asyncio.gather(
  File "/var/task/models/vidsrcme.py", line 35, in vidsrcme
    _encoded = _html.find("div", {"id": "hidden"}).get("data-h")`

**Comment by gabinfinity** [comment]
This API returns vidsrc.to subtitles https://github.com/Aijazmakerb/vidsrc-api

is it possible to add it on your python api?

**Comment by cool-dev-guy** [comment]
> This API returns vidsrc.to subtitles https://github.com/Aijazmakerb/vidsrc-api
> 
> is it possible to add it on your python api?

Yea i will push a new update,i am currently working on many other sources like upcloud,streambucket,mixdrop,etc. so thats why bug fixes are slow and losing interest is also another factor.

**Comment by gabinfinity** [comment]
Oh okay. By the way, about base 64 decode, i saw this repo, i tested and looks fine, it doesnt returns wrong links

https://github.com/habitual69/VidSrc-Streamer/blob/main/helper/vidsrc_extractor.py

**Comment by cool-dev-guy** [comment]
hey i checked the code,what id does is that it recursively sends the request to the domain,and decodes it ,its similar to requesting again,but i think i will add it ,thanks :)

**Comment by cool-dev-guy** [comment]
Added some bug fixes for vidsrc pro(now there wont be any broken links & internal server errors)

**Comment by cool-dev-guy** [comment]
Added `/subs` route,so now when you put:
`/subs?url=subtitle_url@opensubtitles.org` it will retrun a .vtt file,which can be loaded to webpages using `<track caption>`

**Comment by gabinfinity** [comment]
Oh thanks i will update it again

**Comment by gabinfinity** [comment]
I think it still returning something like this, but probably its a return from www.base64decode.org site
![image](https://github.com/cool-dev-guy/vidsrc-api/assets/59806981/5671b0eb-60bb-46f9-a31b-0e4c79b0c2db)
![image](https://github.com/cool-dev-guy/vidsrc-api/assets/59806981/9dd7caef-bd9d-41ed-9dc7-d778dc4717ea)

**Comment by gabinfinity** [comment]
sometimes im getting timeout too

**Comment by gabinfinity** [comment]
sometimes im getting timeout too

![image](https://github.com/cool-dev-guy/vidsrc-api/assets/59806981/f6b1712d-e264-46e4-a850-777145bdf07a)

**Comment by gabinfinity** [comment]
sometimes still returning wrong things on url, seems something related to decode, would be nice a check with https and m3u8 again. After a return "No printable characters found, try another source character set, or upload your data as a file for binary decoding." the second call normally returns a valid URL, but when you access it, it returns a 404 error

![image](https://github.com/cool-dev-guy/vidsrc-api/assets/59806981/3e6aaae9-68ae-4216-9b9a-0ebca3daf68b)
------------
![image](https://github.com/cool-dev-guy/vidsrc-api/assets/59806981/dccde617-8c40-455d-9587-aa7c5368b921)
------------
![image](https://github.com/cool-dev-guy/vidsrc-api/assets/59806981/59ed9780-facf-4c05-8ff9-16d4525f6767)

**Comment by cool-dev-guy** [comment]
- This message : No printable characters found, try another source character set, or upload your data as a file for binary decoding

      is because there was some error in the request(not the decoding part)(will do a bug fix)

- You can prevent the broken url's by increasing the number of `max_attempts` and using a good url validator(will do a bug fix soon)

**Comment by gabinfinity** [comment]
Oh, okay, i'll wait, thank you for this awesome project

**Comment by gabinfinity** [comment]
By the way, would be nice return all these language subtitles

![image](https://github.com/cool-dev-guy/vidsrc-api/assets/59806981/c6eda80d-7f16-40a0-af97-e2cd32568162)

**Comment by cool-dev-guy** [comment]
Language subtitles for vidsrc.me are fetched from opensubtitles.org so you can request with any language like `en` in the url parameter `l`(language).It will return the subs in that language.

I will add vidsrc.to subs

**Comment by gabinfinity** [comment]
But does it supports multiple language search? They have a lot subtitles for each language, would be nice scrap all of them. Would be nice add vidsrc.to subtitles on /extra route too. And i think they changed the encryption methods.

**Comment by gabinfinity** [comment]
I think vidsrc.me changed the encryption. Links are no longer decrypting

**Comment by gabinfinity** [comment]
I think vidsrc.to is not working for TV SHOW: https://vidsrcme.braflix.app/extra/63174?s=1&e=1

Its returning 500 internal server error

![image](https://github.com/cool-dev-guy/vidsrc-api/assets/59806981/fc9d2893-3c6c-4202-ab8e-bfdff5be2b36)
![image](https://github.com/cool-dev-guy/vidsrc-api/assets/59806981/4f5f50d1-014d-49c4-b891-a3d08eaad4b4)

**Comment by cool-dev-guy** [comment]
> I think vidsrc.to is not working for TV SHOW: https://vidsrcme.braflix.app/extra/63174?s=1&e=1
> 
> Its returning 500 internal server error
> 
> ![image](https://private-user-images.githubusercontent.com/59806981/299529110-fc9d2893-3c6c-4202-ab8e-bfdff5be2b36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMzA2ODksIm5iZiI6MTcwNjMzMDM4OSwicGF0aCI6Ii81OTgwNjk4MS8yOTk1MjkxMTAtZmM5ZDI4OTMtM2M2Yy00MjAyLWFiOGUtYmZkZmY1YmUyYjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDA0Mzk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NDQ1N2M5MjRkMDMwODgzMTY3OGM1ZWFhYzNlMDRhNDIzN2I0ZjM2N2IyOTI3YTliNzUyZmVmZjlmY2ViNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ivnh6SqcEWOEl6CCWH3bjNOEaCLMymuADex2KMm-4kI) ![image](https://private-user-images.githubusercontent.com/59806981/299529123-4f5f50d1-014d-49c4-b891-a3d08eaad4b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMzA2ODksIm5iZiI6MTcwNjMzMDM4OSwicGF0aCI6Ii81OTgwNjk4MS8yOTk1MjkxMjMtNGY1ZjUwZDEtMDE0ZC00OWM0LWI4OTEtYTNkMDhlYWFkNGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDA0Mzk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1YmJmZDNiYTkwYTkzOWE0ZWQ1ZTIyZGY3ZGM4NjBhNzYyOGQwY2YwMGFhODgzZmVjODc0MjY3OGM4Y2VkNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.okUnZdJWHORR_tGGK1GiIUYPZeDYOfrrpdTYuf-Knrg)

Hey @gabinfinity i will do a bug fix for this,currently i am working on vidsrc.me extractor cuz it stoped working.(vidsrc.me changed their encoding style)(So there are many impurities that have been added to base64 text,so decoding it will return in a broken url)

**Comment by gabinfinity** [comment]
Oh https://github.com/Ciarands/vidsrc-me-resolver Ciarands fixed it, he said that he fixed base64 decode problem too, but i dont know python to fix it

**Comment by cool-dev-guy** [comment]
Yeah he fixed it currently i am rewriting the code of the api(he is great)

**Comment by gabinfinity** [comment]
oh thats its a good news, i fixed mine too, but still with decode problems

**Comment by cool-dev-guy** [comment]
Yea the error is fixed but the response-time has become large,i need to optimize it

**Comment by gabinfinity** [comment]
okay bro, i'll wait, thank you again

**Comment by cool-dev-guy** [comment]
I have updated the api

**Comment by cool-dev-guy** [comment]
Also added subtitles for every providers

**Comment by gabinfinity** [comment]
Its working really fine now bro. Just a note: Ciarands recommends dont get keys directly pro github raw (https://github.com/Ciarands/vidsrc-keys)
![image](https://github.com/cool-dev-guy/vidsrc-api/assets/59806981/732e6a82-4ce2-4b5a-af30-666787465cbe)

**Comment by Junime** [comment]
how do you host it locally please help with local it just gets stuck on loop and doesnt provide any results, says Internal Server Error

INFO:     Will watch for changes in these directories: ['C:\\Users\\theju\\Desktop\\vidsrc-api']
INFO:     Uvicorn running on http://127.0.0.1:3001 (Press CTRL+C to quit)
INFO:     Started reloader process [1736] using WatchFiles
INFO:     Started server process [18116]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:49487 - "GET / HTTP/1.1" 200 OK
0
0
INFO:     127.0.0.1:49488 - "GET /vidsrc/297802 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
