### ISSUE TITLE
Fetch filemoon embed url

### ISSUE THREAD

**Issue by Rhiannon99** [cool-dev-guy/vidsrc-api#21]
Hello cool guy thank you so much for this, i just want to ask u if it's possible to fetch embed url of filemoon server i want to clone files to my account thanks and what file i can modify

**Comment by Tommy0412** [comment]
Added filemoon url, Check my repo https://github.com/Tommy0412/vidsrc-api-py

**Comment by Rhiannon99** [comment]
> Added filemoon url, Check my repo https://github.com/Tommy0412/vidsrc-api-py

Thank you so much bro you are a hero

**Comment by Rhiannon99** [comment]
> Added filemoon url, Check my repo https://github.com/Tommy0412/vidsrc-api-py

Hello bro can please fix the api i just need the filemoon embed urls if it's possible thank you I'll buy u some coffee

**Comment by Tommy0412** [comment]
> > Added filemoon url, Check my repo https://github.com/Tommy0412/vidsrc-api-py
> 
> Hello bro can please fix the api i just need the filemoon embed urls if it's possible thank you I'll buy u some coffee

contact me on telegram Tommy0412 and i will give a script in php for that purpose.

**Comment by Rameshkumarsahutmr** [comment]
May u plz say how to use it .. I have deployed on vecel but don't know how to work ..what is the base url and and all

**Comment by cool-dev-guy** [comment]
New repo : https://github.com/cool-dev-guy/vidsrc.ts
