### ISSUE TITLE
Vidplay source blank

### ISSUE THREAD

**Issue by cts-cts** [cool-dev-guy/vidsrc-api#22]
bro, I'm getting blank data on Vidplay source. can you fix it, please? also Filemoon source got 404.

`{
"status": 200,
"info": "success",
"sources": [
{
"name": "Vidplay",
"data": {}
},
{
"name": "Filemoon",
"data": {
"stream": "https://be6224.rcr92.lim01.cdn112.com/hls2/01/01947/cem677z8yclh_x/master.m3u8?t=Y1N51ETQv8_daJmuiFk7ASbImHEspZ2BRQIySTtjBMk&s=1716027596&e=43200&f=19003911&srv=14&asn=14618&sp=5500",
"subtitle": [
{
"lang": "Arabic",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14018524.vtt"
},
{
"lang": "Bengali",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14018536.vtt"
},
{
"lang": "Brazillian Portuguese",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14018558.vtt"
},
{
"lang": "Bulgarian",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14018578.vtt"
},
{
"lang": "Chinese (BG code)",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14018603.vtt"
},
{
"lang": "Croatian",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14018616.vtt"
},
{
"lang": "Czech",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019446.vtt"
},
{
"lang": "Danish",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14018675.vtt"
},
{
"lang": "Dutch",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14018690.vtt"
},
{
"lang": "English",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14018438.vtt"
},
{
"lang": "Farsi/Persian",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14018718.vtt"
},
{
"lang": "Finnish",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14018725.vtt"
},
{
"lang": "French",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14018736.vtt"
},
{
"lang": "German",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14018800.vtt"
},
{
"lang": "Greek",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14018828.vtt"
},
{
"lang": "Indonesian",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14018958.vtt"
},
{
"lang": "Korean",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019037.vtt"
},
{
"lang": "Malay",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019096.vtt"
},
{
"lang": "Malayalam",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019132.vtt"
},
{
"lang": "Norwegian",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019146.vtt"
},
{
"lang": "Polish",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019158.vtt"
},
{
"lang": "Portuguese (Brazilian)",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019434.vtt"
},
{
"lang": "Portuguese",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019173.vtt"
},
{
"lang": "Romanian",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019234.vtt"
},
{
"lang": "Russian",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019242.vtt"
},
{
"lang": "Serbian",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019256.vtt"
},
{
"lang": "Sinhala",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019266.vtt"
},
{
"lang": "Slovenian",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019293.vtt"
},
{
"lang": "Spanish",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019343.vtt"
},
{
"lang": "Sundanese",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019352.vtt"
},
{
"lang": "Swedish",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019360.vtt"
},
{
"lang": "Thai",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019370.vtt"
},
{
"lang": "Urdu",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019423.vtt"
},
{
"lang": "Vietnamese",
"file": "https://rapidcdn.cc/sub/cache/subtitle/14019428.vtt"
}
]
}
}
]
}`

**Comment by 0x86e3x4** [comment]
He/she/it made a fix long time a go. he has a repo to bypass turnstile called futurn i suggest adapting it in your own logic.
the streams will work

**Comment by cool-dev-guy** [comment]
New repo : https://github.com/cool-dev-guy/vidsrc.ts
