### ISSUE TITLE
Stream link does work on my local, but it does not work on vercel

### ISSUE THREAD

**Issue by darwincringe** [cool-dev-guy/vidsrc-api#23]
Hey cool guy, i wanted to thank you for this repo.
Here is my vercel https://vidsrc-api-resolver-kappa.vercel.app/vidsrc/tt2911666
When I open the stream it says 404 Not Found nginx, and does not work on VLC.
But It does work on my local, I dont understand why, i changed the node to 18 still same error
Can you please help?

**Comment by cool-dev-guy** [comment]
New repo : https://github.com/cool-dev-guy/vidsrc.ts
