### ISSUE TITLE
Deployed on vercel but no sources are coming up

### ISSUE THREAD

**Issue by fvision8** [cool-dev-guy/vidsrc-api#25]
Thanks for your work. I was able to deploy on vercel using the button from your main page and it was successfuly built and deployed.
Unfortunately when I try to get sources via API call, it doesn't return anything.
Any suggestions?

![image](https://github.com/user-attachments/assets/e8f646f8-a837-4c4b-89c4-756c932715c4)

![image](https://github.com/user-attachments/assets/22275224-299c-4a2f-ade8-d64dbc2f390c)

**Comment by papi028** [comment]
im getting same issue

**Comment by cool-dev-guy** [comment]
New repo : https://github.com/cool-dev-guy/vidsrc.ts
