### ISSUE TITLE
Lets make this Scraper work again

### ISSUE THREAD

**Issue by koiraladarwin** [cool-dev-guy/vidsrc-api#28]
I am just writting this to as a form to contact you. I want to make some cool stuff like this one you did . make a app or website or anything where user can get ad free experince. more than anything i wanna get better at code. just hit me up cause i want people who like to code to work togehter and imporve our craft . darwinmage98422@gmail.com

**Comment by cool-dev-guy** [comment]
> I am just writting this to as a form to contact you. I want to make some cool stuff like this one you did . make a app or website or anything where user can get ad free experince. more than anything i wanna get better at code. just hit me up cause i want people who like to code to work togehter and imporve our craft . [darwinmage98422@gmail.com](mailto:darwinmage98422@gmail.com)

@BatmanBoxer
New repo :
https://github.com/cool-dev-guy/vidsrc.ts
