### ISSUE TITLE
support with localhost needed

### ISSUE THREAD

**Issue by Junime** [cool-dev-guy/vidsrc-api#4]
how do you host it locally please help with local it just gets stuck on loop and doesnt provide any results, says Internal Server Error

INFO: Will watch for changes in these directories: ['C:\Users\theju\Desktop\vidsrc-api']
INFO: Uvicorn running on http://127.0.0.1:3001/ (Press CTRL+C to quit)
INFO: Started reloader process [1736] using WatchFiles
INFO: Started server process [18116]
INFO: Waiting for application startup.
INFO: Application startup complete.
INFO: 127.0.0.1:49487 - "GET / HTTP/1.1" 200 OK
0
0
INFO: 127.0.0.1:49488 - "GET /vidsrc/297802 HTTP/1.1" 500 Internal Server Error
ERROR: Exception in ASGI application

**Comment by cool-dev-guy** [comment]
It works perfectly using `uvicorn` locally.
you can just run it using it.Also i cant reproduce the error,so can you add additional details of the issue?Like whether this issue is there for other ids?
