### ISSUE TITLE
How to get episode  source from seasons?

### ISSUE THREAD

**Issue by fsmdeveloper** [cool-dev-guy/vidsrc-api#5]
I want to get an episode for a specific season. like I want to get game of Thrones season 1 episode 1 source.

parameters:

```
s - season (series only)
e - episodes (series only)
l - language(subtitle)
```

I don' understand this parameters.

can you tell me the example endpoint for series/season/episode?

**Comment by fsmdeveloper** [comment]
also can i port this project for nodejs?

**Comment by cool-dev-guy** [comment]
> I want to get an episode for a specific season. like I want to get game of Thrones season 1 episode 1 source.
> 
> parameters:
> 
> ```
> s - season (series only)
> e - episodes (series only)
> l - language(subtitle)
> ```
> 
> I don' understand this parameters.
> 
> can you tell me the example endpoint for series/season/episode?

the url for a series will be:
```
https://api-movie-source.vercel.app/vidsrc/tmdb_id-or-imdb_id?s=1&e=1
https://api-movie-source.vercel.app/vsrcme/tmdb_id-or-imdb_id?s=1&e=1
```
`l` is for language by default its `eng`.

**Comment by fsmdeveloper** [comment]
thank you so much!! if I convert this project to nodejs with cheerio (it's like BeautifulSoup) package, will it work? what do you think?

**Comment by cool-dev-guy** [comment]
Yea it can be converted to node using cheerio and so,but will be hard to do the extractors

- packed-extractor
- hunter-extractor

so you may need to research and find out.

**Comment by fsmdeveloper** [comment]
Thank you! I have a question: Does this Python project's API depend on any special key, like https://keys4.fun/, or does it retrieve necessary information from an embedded URL

**Comment by cool-dev-guy** [comment]
> Thank you! I have a question: Does this Python project's API depend on any special key, like https://keys4.fun/, or does it retrieve necessary information from an embedded URL

it uses a key extractor developed by ciarands for vidplay keys,since they change after some time.Other all streams are available without external keys.

**Comment by fsmdeveloper** [comment]
`[
    {
        "name": "VidSrcPRO",
        "data": {
            "file": "https://s4.putgate.org/cdn/H4sIAAAAAAAAAxXMwW6DIBgA4FdSQG2X7NJVcGZgkAKD2y.OWKvL0hjS.PTtrt_hixWgHABnkVSQx1gM8TjgQ4UOx5dk1VvAvQXmGeC.6.yDdEaUDn2SzhazsC26WKrDTHloTDsgfh.p8cHSZBrKNBNTaOhdYp8ue2_Udduk2krBikXR5drf2g.HXKbXDX7qvxnqsZbf086bU6nR4pTN__sEO01qGVM435D5Nd5pL_nKSaAi.XNLhnWSX9i9PwHVPnphzQAAAA--/list.m3u8",
            "sub": [
                {
                    "lang": "eng",
                    "file": "https://api-vidsrc-rouge.vercel.app/subs?url=https://dl.opensubtitles.org/en/download/src-api/vrf-19b80c5d/filead/1954116988.gz"
                }
            ]
        }
    },
    {
        "name": "SuperEmbed",
        "data": {
            "file": "1308 https://multiembed.mov/directstream.php?video_id=tt1981115",
            "sub": "1981115"
        }
    }
]`

I am getting m3u8 from VidSrcPRO but not from SuperEmbed, why? I've got **`https://multiembed.mov/directstream.php?video_id=tt1981115`** [embed url]

any solution?

**Comment by cool-dev-guy** [comment]
> `[ { "name": "VidSrcPRO", "data": { "file": "https://s4.putgate.org/cdn/H4sIAAAAAAAAAxXMwW6DIBgA4FdSQG2X7NJVcGZgkAKD2y.OWKvL0hjS.PTtrt_hixWgHABnkVSQx1gM8TjgQ4UOx5dk1VvAvQXmGeC.6.yDdEaUDn2SzhazsC26WKrDTHloTDsgfh.p8cHSZBrKNBNTaOhdYp8ue2_Udduk2krBikXR5drf2g.HXKbXDX7qvxnqsZbf086bU6nR4pTN__sEO01qGVM435D5Nd5pL_nKSaAi.XNLhnWSX9i9PwHVPnphzQAAAA--/list.m3u8", "sub": [ { "lang": "eng", "file": "https://api-vidsrc-rouge.vercel.app/subs?url=https://dl.opensubtitles.org/en/download/src-api/vrf-19b80c5d/filead/1954116988.gz" } ] } }, { "name": "SuperEmbed", "data": { "file": "1308 https://multiembed.mov/directstream.php?video_id=tt1981115", "sub": "1981115" } } ]`
> 
> I am getting m3u8 from VidSrcPRO but not from SuperEmbed, why? I've got **`https://multiembed.mov/directstream.php?video_id=tt1981115`** [embed url]
> 
> any solution?

you can reload it again it will work,its rare to get that error.
Btw its working when i tried.

**Comment by fsmdeveloper** [comment]
Yes, I have deployed it on a DigitalOcean droplet, and I am getting this error. When I deployed it to Vercel, then it's working properly. I think they added reCAPTCHA for my VPS (SuperEmbed), that's why my VPS can't get the direct stream URL from SuperEmbed

**Comment by cool-dev-guy** [comment]
> Yes, I have deployed it on a DigitalOcean droplet, and I am getting this error. When I deployed it to Vercel, then it's working properly. I think they added reCAPTCHA for my VPS (SuperEmbed), that's why my VPS can't get the direct stream URL from SuperEmbed

Yea if you are using a vps,they could actually detect the traffic and apply a captcha on it,you can bypass by reloading/solving-captcha/use-vercel(vercel requests differ each time you run it).

**Comment by fsmdeveloper** [comment]
oh, I wasn't aware that `"Vercel requests differ each time you run it"` thank you for your valuable time & info!

**Comment by fsmdeveloper** [comment]
`https://api-movie-source.vercel.app/vsrcme/tt1630029`

```
    {
        "name": "SuperEmbed",
        "data": {
            "file": "1308 https://multiembed.mov/directstream.php?video_id=tt0944947&s=1&e=1",
            "sub": "944947_1x1"
        }
    }
```

brother, not getting stream links from SuperEmbed. still the same issue on vercel. any solution?

**Comment by cool-dev-guy** [comment]
Ig they blocked my requests lol,changing the domain will fix it

**Comment by fsmdeveloper** [comment]
if I use the proxy, will it bypass it?

**Comment by cool-dev-guy** [comment]
> if I use the proxy, will it bypass it?

Hey @fsmdeveloper it was a bug actually,i fixed it and now it works,Thank you for reporting.

**Comment by fsmdeveloper** [comment]
Thank you, bro! It's working now.

Currently, streaming links are being obtained from "**VidSrcPRO**" and "**SuperEmbed**".

Can I get them from other servers like **"vidplay" and "vidsrcto"?**

**Comment by cool-dev-guy** [comment]
> Thank you, bro! It's working now.
> 
> Currently, streaming links are being obtained from "**VidSrcPRO**" and "**SuperEmbed**".
> 
> Can I get them from other servers like **"vidplay" and "vidsrcto"?**

use `https://api-movie-source.vercel.app/vsrcme/tt1630029` instead of `https://api-movie-source.vercel.app/vidsrc/tt1630029` to get vidplay files.

**Comment by fsmdeveloper** [comment]
**`{{BASE_URL}}/vidsrc/tt1630029`**

```
[
    {
        "name": "Vidplay",
        "data": 1401
    },
    {
        "name": "Filemoon",
        "data": 1402
    }
]
```
Not getting any streaming links.

**Comment by cool-dev-guy** [comment]
Works now : https://api-source-movie.vercel.app/vidsrc/tt1630029
actually these errors maybe due to their server outage...Or maybe some other reason.

**Comment by fsmdeveloper** [comment]
same output, still not working

```
[
{
"name": "Vidplay",
"data": 1401
},
{
"name": "Filemoon",
"data": 1402
}
]
```
