### ISSUE TITLE
Vidsrc.to returning only Auto quality for movies

### ISSUE THREAD

**Issue by gabinfinity** [cool-dev-guy/vidsrc-api#6]
Hey cool-guy, im using your vidsrc.to api for my website and i realized today that is returning only Auto quality until yestarday it was returning all qualities, Auto, 1080p, 720p, 360. I checked on vidsrc.to site to see if they still with all thoso qualities, and it is. By the way, only movies have this problem with only Auto quality, TV Shows still with multiple quality

**Comment by gabinfinity** [comment]
its not happening anymore. But there is a new problem, i think the subtitles urls is outdated, i tested with Lucifer TV Show and Barbie, and the urls is returning timed-out. You can check here: https://s3.bunnycdn.ru/sub/cache3/subtitle/14225190.vtt

**Comment by gabinfinity** [comment]
seems the new url is https://rapidcdn.cc/sub/cache/subtitle/13022700.vtt

**Comment by cool-dev-guy** [comment]
> seems the new url is https://rapidcdn.cc/sub/cache/subtitle/13022700.vtt

Hey @gabinfinity ,Sorry i was busy so i couldn't fix the errors,But i guess it works now.Please tell me if the error still exist.Thank you for reporting the issue.

**Comment by gabinfinity** [comment]
no problem, yeah it fixed alone :D i would like to ask if its possible to scrap specific qualities from vidsrc.to, like 1080p, currently its scraps only auto quality

**Comment by gabinfinity** [comment]
i think vidsrc.to/vidplay updated something, the api isnt returnign sources anymore

**Comment by gabinfinity** [comment]
I just fixed it: https://github.com/gabinfinity/vidsrc-api/commit/a830b09a397a395bcb62eda03e2216069d581c75

But the subtitles is not working anymore. I dont know if it can help you, but this subtitles seems to work https://github.com/streamflix-one/providers/blob/main/scrapers/subtitles.py

maybe you can add it on your API

**Comment by gabinfinity** [comment]
By the way, today the tv shows just stop to work, api cant scrap it anymore

**Comment by gabinfinity** [comment]
well for some reason, your api url works pretty fine, but when we fork and host it, it doesnt works

https://api-movie-source.vercel.app/vidsrc/792307
https://vidsrc-api-six.vercel.app/vidsrc/87818

**Comment by cool-dev-guy** [comment]
> well for some reason, your api url works pretty fine, but when we fork and host it, it doesnt works
> 
> https://api-movie-source.vercel.app/vidsrc/792307 https://vidsrc-api-six.vercel.app/vidsrc/87818

hey @gabinfinity the recent commit should have fixed the vidplay issue.
Also i dont think the issue of the tvshows is related to the api because those shows arent available on vidsrc.me or vidsrc.to.
