### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by Rhiannon99** [cool-dev-guy/vidsrc-api#7]
Fetching subtitles is not working, anyway thank you so much much for this respo

**Comment by gabinfinity** [comment]
He pushed some commits today, but for me still now working, is it working for you?

**Comment by cool-dev-guy** [comment]
Hey,Please also mention about which route is facing the issue,The recent commit should have fixed some issues.

**Comment by Inside4ndroid** [comment]
this route does not work as it returns a 402 payment required :

sub_base_url = "https://api-vidsrc-rouge.vercel.app/subs?url="

i replaced this with the url of my deployment and the subs started working again.

**Comment by cool-dev-guy** [comment]
> this route does not work as it returns a 402 payment required :
> 
> sub_base_url = "https://api-vidsrc-rouge.vercel.app/subs?url="
> 
> i replaced this with the url of my deployment and the subs started working again.

yea it was one of the old deployments so it wont work,I have updated the code and written in the `readme` to change that url to the `deployment_url`.
